apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sw-movie-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lolek1979/sw-movie-app.git'
    targetRevision: HEAD
    path: .  # Adjust if your Kubernetes manifests live in a subdirectory
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true